site_name: SAP02 Notes
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/jayramj"  target="_blank" rel="noopener">Jayram Joshi</a>

markdown_extensions:
  - tables:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
